#default browser: chrome
#default environment: test1

browsers:
#  chrome: CHROME
#  firefox: FIREFOX
#  ie: IE
#  edge: EDGE

environment:
  test1:
    envName: test1
    webUrl: http://146.59.32.4/
    title: TesterSii
    login: userTest1
    password: passwordTest1
    existingEmail: existingemail@email.com
    existingPassword: haslo5
#    active: true

  test2:
    envName: test2
    webUrl: http://automationpractice.com/
    title: My Store
    login: userTest2
    password: passwordTest2
#    active: true

  prod:
    envName: prod
    webUrl: https://www.filmweb.pl/
    title: Filmweb - filmy takie jak Ty!
    login: userProd
    password: passwordProd
#    active: true














